/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package a20170920;

import a20170913.*;
import java.util.Scanner;

/**
 *
 * @author Misaka
 */
public class KovacsGabor_szemszamgui extends javax.swing.JFrame {

    /**
     * Creates new form ablak
     */
    public KovacsGabor_szemszamgui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("ellenörzés");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(54, 54, 54)
                        .addComponent(jLabel2)))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jButton1))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2))
                    .addComponent(jLabel3))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jLabel1.setText("");
         jLabel2.setText("");
          jLabel3.setText("");
          
        String szam = jTextField1.getText();
        szamolas(szam);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void szamolas(String szam){
        String sem = szam;
        int osszeg = 0;
        int k = Integer.parseInt(sem.substring(10, 11));
        int sev = Integer.parseInt(sem.substring(1, 2)) * 10 + Integer.parseInt(sem.substring(2, 3));
        int j = 0;
        if (sev <= 96) {
            for (int i = 0; i < 10; i++) {
                j++;
                osszeg = osszeg + ((Integer.parseInt(sem.substring(i, j))) * j);
            }
            if (osszeg % 11 == k) {
                //System.out.println("Rendben");
                jLabel1.setText("rendben");
                nem(Integer.parseInt(sem.substring(0, 1)));
            } else {
                hibas();
            }
        } else if (sev>96) {
            int sorzo = 10;
            for (int i = 0; i < 10; i++) {
                j++;
                osszeg = osszeg + Integer.parseInt(sem.substring(i, j)) * sorzo;
                sorzo--;
            }
            if (osszeg % 11 == Integer.parseInt(sem.substring(10, 11))) {
                //System.out.println("Rendben");
                jLabel1.setText("rendben");
                nem(Integer.parseInt(sem.substring(0, 1)));
            } else {
                hibas();
            }

        } else {
            hibas();
        }
    }
    private  void hibas() {
        System.out.println("rossz");
        jLabel1.setText("rossz");
        
    }
     private  void nem(int nem){
        int nemek = nem;
    if (nemek%2==0) {
                    //System.out.println("nő");
                    jLabel2.setText("nő");
                }
                else{
                    //System.out.println("férfi");
                    jLabel2.setText("férfi");
                }
    
    if (nemek>4) {
        System.out.println("Kései magyar");
        jLabel3.setText("kései magyar");
    }  
    else{
        System.out.println("igaz magyar");
        jLabel3.setText("igaz magyar");
    }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KovacsGabor_szemszamgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KovacsGabor_szemszamgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KovacsGabor_szemszamgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KovacsGabor_szemszamgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KovacsGabor_szemszamgui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
